import Link from "next/link";
import { Check } from "lucide-react";
import { marketingId } from "@/lib/i18n/id/marketing";
const tiers = [
  { name: "Free", price: "Gratis", tagline: "Untuk mencoba alur penerbitan.", features: ["50 kredit per bulan", "3 proyek aktif", "1 ebook terbit", "Tautan klaim tanpa batas"], label: "Mulai gratis", featured: false },
  { name: "Creator", price: "Rp299 ribu", tagline: "Untuk kreator mandiri.", features: ["500 kredit per bulan", "Proyek aktif tanpa batas", "10 ebook terbit", "Ekspor PDF dan EPUB", "Analitik klaim dasar"], label: "Pilih Creator", featured: true },
  { name: "Pro", price: "Rp749 ribu", tagline: "Untuk tim kecil dengan ritme tinggi.", features: ["2.000 kredit per bulan", "Ebook terbit tanpa batas", "Antrean pembuatan prioritas", "Ekspor data klaim CSV", "Sampul dengan merek sendiri"], label: "Pilih Pro", featured: false },
] as const;
export function Pricing() { return <section id="pricing" className="bg-white"><div className="mx-auto max-w-7xl px-4 py-14 sm:px-6 md:py-20"><div className="mx-auto max-w-3xl text-center"><p className="text-xs font-semibold uppercase tracking-[0.16em] text-[var(--color-publiora-blue)]">{marketingId.pricing.eyebrow}</p><h2 className="mt-3 text-3xl font-bold tracking-tight text-balance text-[var(--color-publiora-black)] sm:text-4xl">{marketingId.pricing.title}</h2><p className="mt-4 leading-relaxed text-[var(--color-medium-gray)]">{marketingId.pricing.description}</p><ul className="mt-5 space-y-1 text-sm text-[var(--color-deep-gray)]">{marketingId.pricing.creditCosts.map((fact) => <li key={fact}>{fact}</li>)}</ul><p className="mt-3 text-sm font-medium text-[var(--color-deep-gray)]">{marketingId.pricing.topUp}</p></div><div className="mt-12 grid items-stretch gap-4 lg:grid-cols-3">{tiers.map((tier) => <article key={tier.name} className={`relative flex rounded-[var(--radius-card)] border bg-white p-6 ${tier.featured ? "border-[var(--color-publiora-black)] shadow-[var(--shadow-pop)]" : "border-[var(--color-publiora-border)]"}`}><div className="flex w-full flex-col">{tier.featured && <span className="absolute -top-3 left-6 rounded-full bg-[var(--color-gold)] px-3 py-1 text-xs font-semibold text-[var(--color-publiora-black)]">Paling populer</span>}<h3 className="text-sm font-semibold uppercase tracking-[0.14em] text-[var(--color-medium-gray)]">{tier.name}</h3><p className="mt-3"><span className="text-3xl font-bold text-[var(--color-publiora-black)]">{tier.price}</span>{tier.price !== "Gratis" && <span className="ml-1 text-sm text-[var(--color-medium-gray)]">{marketingId.pricing.monthly}</span>}</p><p className="mt-2 text-sm text-[var(--color-medium-gray)]">{tier.tagline}</p><ul className="mt-6 flex-1 space-y-3 text-sm">{tier.features.map((feature) => <li key={feature} className="flex items-start gap-2"><Check aria-hidden="true" className="mt-0.5 h-4 w-4 shrink-0 text-[var(--color-success)]" /><span>{feature}</span></li>)}</ul><Link href="/register" className={`mt-7 inline-flex min-h-11 w-full items-center justify-center rounded-[var(--radius-button)] border px-3.5 text-sm font-medium transition-colors focus-visible:outline-2 focus-visible:outline-offset-2 ${tier.featured ? "border-transparent bg-[var(--color-publiora-black)] text-[var(--color-publiora-white)] shadow-sm hover:bg-[var(--color-deep-gray)]" : "border-[var(--color-border-subtle)] bg-transparent text-[var(--color-deep-gray)] hover:bg-[var(--color-surface-2)]"}`}>{tier.label}</Link></div></article>)}</div></div></section>; }
